
const SH_TIMER_PRECISION             = 1;

const SH_TIMER_STATE_STOPPED         = 0;
const SH_TIMER_STATE_PLAYING         = 1;

const SH_TIMER_DEFAULT_TIME          = 0;
const SH_TIMER_DEFAULT_INTERVAL      = 1000;
const SH_TIMER_DEFAULT_PLAYSTATE     = SH_TIMER_STATE_STOPPED;
const SH_TIMER_DEFAULT_SPEED         = 1;
const SH_TIMER_DEFAULT_BOTTOM_CAP    = Number.NEGATIVE_INFINITY;
const SH_TIMER_DEFAULT_TOP_CAP       = Number.POSITIVE_INFINITY;
const SH_TIMER_DEFAULT_LOOP          = false;
const SH_TIMER_DEFAULT_RAISES_EVENTS = true;
